apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-call-mood-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-call-mood-listener
  template:
    metadata:
      labels:
        app: data-call-mood-listener
    spec:
      volumes:
      - name: apkey
        secret:
          secretName: appssecret
      containers:
      - name: data-call-mood-listener
        image: data-call-mood-listener:1
        # for local development against minikube registry
        #imagePullPolicy: Never        
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: apkey
          mountPath: /server/config/local-certmanager-config.json
          subPath: certmanager
        - name: apkey
          mountPath: /server/config/local-kvs-config.json
          subPath: kvs
        - name: apkey
          mountPath: /server/config/local-mongo-config.json
          subPath: mongodb
        - name: apkey
          mountPath: /server/config/local-cloudant-config.json
          subPath: cloudantdb
        - name: apkey
          mountPath: /server/config/connection-profile.json
          subPath: connectionprofile
---
apiVersion: v1
kind: Service
metadata:
  name: data-call-mood-listener
  labels:
    app: data-call-mood-listener
spec:
  #type: NodePort
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
    # the port that this service should serve on
    #- port: 8080
    #  targetPort: 8080
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: data-call-mood-listener
---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: data-call-mood-listener-ingress
#   annotations:
#     kubernetes.io/ingress.class: "public-iks-k8s-nginx"
# spec:
#   tls:
#   - hosts:
#     - data-call-mood-listener.aais.us-east.containers.appdomain.cloud
#     secretName: aais
#   rules:
#   - host: data-call-mood-listener.aais.us-east.containers.appdomain.cloud
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: data-call-mood-listener
#           servicePort: 8080  