apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-data-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-data-manager
  template:
    metadata:
      labels:
        app: insurance-data-manager
    spec:
      volumes:
      - name: apkey
        secret:
          secretName: appssecret
      containers:
      - name: insurance-data-manager
        image: openidl/insurance-data-manager
        # for local development against minikube registry
        imagePullPolicy: Never        
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: apkey
          mountPath: /server/config/local-appid-config.json
          subPath: appid
        - name: apkey
          mountPath: /server/config/local-cognito-config.json
          subPath: cognito
        - name: apkey
          mountPath: /server/config/local-certmanager-config.json
          subPath: certmanager
        - name: apkey
          mountPath: /server/config/local-mongo-config.json
          subPath: mongodb
        - name: apkey
          mountPath: /server/config/local-cloudant-config.json
          subPath: cloudantdb
        - name: apkey
          mountPath: /server/config/connection-profile.json
          subPath: connectionprofile
        # resources:
        #   requests:
        #     cpu: "0.2"
        #     memory: "2Gi"
        #   limits:
        #     cpu: "0.3"
        #     memory: "3Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-data-manager
  labels:
    app: insurance-data-manager
spec:
  #type: NodePort
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
    # the port that this service should serve on
    #- port: 8080
    #  targetPort: 8080
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: insurance-data-manager
---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: insurance-data-manager-ingress
#   annotations:
#     kubernetes.io/ingress.class: "public-iks-k8s-nginx"
#     ingress.bluemix.net/client-max-body-size: serviceName=insurance-data-manager size=500m; size=500m
# spec:
#   tls:
#   - hosts:
#     - insurance-data-manager.aais.us-east.containers.appdomain.cloud
#     secretName: aais
#   rules:
#   - host: insurance-data-manager.aais.us-east.containers.appdomain.cloud
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: insurance-data-manager
#           servicePort: 8080  
