name: Publish openIDL data-call-app
on:
  push:
    branches:
      - 'develop'
    paths:
      - 'openidl-data-call-app/**'

  workflow_dispatch:

env:
  REGISTRY: ghcr.io/${{ github.repository }}
  IMAGE_NAME: openidl-data-call-app

defaults:
  run:
    shell: bash
    working-directory: openidl-data-call-app

jobs:
  build-and-push-image-data-call-app:
    name: Build and Push - openIDL data-call-app to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the Repository
        uses: actions/checkout@v2

      - name: Log into GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Prepare .npmrc
        id: npmrc
        run: |
          sed -i 's|${GITHUB_TOKEN}|${{ secrets.GITHUB_TOKEN }}|' ./.npmrc

      - name: Get Current Date and Time
        id: datetime
        run: echo "BUILD_DATETIME=$(date +%m%d%Y%H%M)" >> ${GITHUB_ENV}

      - name: Get Branch Name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> ${GITHUB_ENV}

      - name: Get Commit ID
        run: echo "COMMIT_ID=$(git rev-parse --short "$GITHUB_SHA")" >> ${GITHUB_ENV}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: openidl-data-call-app
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}-${{ env.BRANCH }}-${{ env.COMMIT_ID }}-${{ env.BUILD_DATETIME }}
