name: Publish openIDL utilities
on:
  push:
    branches:
      - 'cognito-fabric-node14-helm'
    paths:
      - 'openidl-utilities/**'

env:
  REGISTRY: ghcr.io/${{ github.repository }}
  IMAGE_NAME: openidl-utilities

defaults:
  run:
    shell: bash
    working-directory: openidl-utilities

jobs:
  build-and-push-image-utilities:
    name: Build and Push - openIDL utilities to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the Repository
        uses: actions/checkout@v2

      - name: Log into GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Prepare .npmrc
        id: npmrc
        run: |
          sed -i 's|${GITHUB_TOKEN}|${{ secrets.GITHUB_TOKEN }}|' ./.npmrc

      - name: Get Current Date and Time
        id: datetime
        run: echo "BUILD_DATETIME=$(date +%m%d%Y%H%M)" >> ${GITHUB_ENV}

      - name: Get Branch Name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> ${GITHUB_ENV}

      - name: Get Commit ID
        run: echo "COMMIT_ID=$(git rev-parse --short "$GITHUB_SHA")" >> ${GITHUB_ENV}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: openidl-utilities
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}-${{ env.BRANCH }}-${{ env.COMMIT_ID }}-${{ env.BUILD_DATETIME }}
