name: Publish openIDL common-lib to Github NPM
on:
  push:
    branches:
      - openidl-nd-poc-main       
      - develop
      - cognito_log
    paths:
      - 'openidl-common-lib/**'
  
  workflow_dispatch:

jobs:
  publish-openidl-common-lib-npm-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create .npmrc
        run: |
          cd openidl-common-lib/
          echo "//npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc
          echo "@openidl-org:registry=https://npm.pkg.github.com" >> .npmrc
          echo "always-auth=true" >> .npmrc
          cat .npmrc
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com/'
      - name: Publish package on NPM
        run: |
          cd openidl-common-lib/
          npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
